### ISSUE TITLE
Add sr only class

### ISSUE THREAD

**Issue by javierarques** [peertransfer/flystyles#8]
```css
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
}
```
